"""Fill {{m:<key>}} placeholders from the metric dictionary and format values by unit (03 §6)."""

import re

from advisor_copilot.models import Metric, Recommendation, RenderedRecommendation

PLACEHOLDER = re.compile(r"\{\{m:([^}]+)\}\}")
DISCLOSURE = (
    "Generated by an AI assistant from fictional demo data for advisor review. Not investment "
    "advice. Figures are illustrative and computed from stated assumptions; verify before "
    "discussing with the client."
)


def format_value(value: float, unit: str) -> str:
    if unit == "pct":
        return f"{value:.1f}%"
    if unit == "pp":
        return f"{value:+.1f} pp"
    if unit == "cad":
        return f"-${abs(value):,.0f}" if value < 0 else f"${value:,.0f}"
    if unit == "years":
        return f"{value:.0f} years"
    return f"{value:.2f}"


def render_text(text: str, metrics: dict[str, Metric]) -> str:
    """Substitute every placeholder; raises KeyError for a key missing from `metrics`."""
    return PLACEHOLDER.sub(lambda m: format_value(metrics[m[1]].value, metrics[m[1]].unit), text)


def render(draft: Recommendation, metrics: dict[str, Metric]) -> RenderedRecommendation:
    def walk(x):  # noqa: ANN001, ANN202
        if isinstance(x, str):
            return render_text(x, metrics)
        if isinstance(x, list):
            return [walk(i) for i in x]
        if isinstance(x, dict):
            return {k: walk(v) for k, v in x.items()}
        return x

    used = sorted(set(PLACEHOLDER.findall(draft.model_dump_json())))
    return RenderedRecommendation(
        recommendation=Recommendation.model_validate(walk(draft.model_dump())),
        disclosure=DISCLOSURE,
        metrics_used=[metrics[k] for k in used],
    )
